// @flow

// Generated by `lerna ls --json`
//
// With new packages, we'll want to run this again, and add to ignores
// Instead of opting for a fully discovered setup from the monorepo, I've opted
// for this package to work when used outside of the monorepo.

module.exports = {
  lernaModules: [
    {
      name: "ansi-to-react",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/commutable",
      version: "6.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/connected-components",
      version: "5.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/core",
      version: "9.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/directory-listing",
      version: "1.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/dropdown-menu",
      version: "0.5.7",
      private: false
    },
    {
      name: "@nteract/editor",
      version: "8.0.0-alpha.0",
      private: false
    },
    {
      name: "enchannel-zmq-backend",
      version: "8.0.0-alpha.0",
      private: false
    },
    {
      name: "fs-observable",
      version: "3.0.2",
      private: false
    },
    {
      name: "@mybinder/host-cache",
      version: "1.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/iron-icons",
      version: "0.2.5",
      private: false
    },
    {
      name: "@nteract/jupyter-widgets",
      version: "1.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/logos",
      version: "0.1.5",
      private: false
    },
    {
      name: "@nteract/markdown",
      version: "3.0.1",
      private: false
    },
    {
      name: "@nteract/mathjax",
      version: "3.0.1",
      private: false
    },
    {
      name: "@nteract/messaging",
      version: "5.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/monaco-editor",
      version: "2.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/notebook-app-component",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/octicons",
      version: "1.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/outputs",
      version: "1.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/presentational-components",
      version: "2.0.0-alpha.0",
      private: false
    },
    {
      name: "rx-binder",
      version: "3.0.0-alpha.0",
      private: false
    },
    {
      name: "rx-jupyter",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/selectors",
      version: "1.0.0",
      private: false
    },
    {
      name: "@nteract/styled-blueprintjsx",
      version: "1.1.1",
      private: false
    },
    {
      name: "@nteract/styleguide-components",
      version: "0.1.4",
      private: false
    },
    {
      name: "@nteract/transform-geojson",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/transform-model-debug",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/transform-plotly",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/transform-vdom",
      version: "3.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/transform-vega",
      version: "4.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/types",
      version: "1.0.0",
      private: false
    },
    {
      name: "@nteract/webpack-configurator",
      version: "2.0.0-alpha.0",
      private: false
    },
    {
      name: "@nteract/stateful-components",
      version: "1.0.0",
      private: false
    },
    {
      name: "@nteract/mythic-notifications",
      version: "0.1.0",
      private: false
    },
    {
      name: "@nteract/myths",
      version: "0.1.0",
      private: false
    },
    {
      name: "@nteract/web",
      version: "1.0.0",
      private: false
    }
  ]
};
